### ISSUE TITLE
Not switching to selling state during questing

### ISSUE THREAD

**Issue by Geigerkind** [Jnnshschl/AmeisenBotX#32]

**Comment by Bia10** [comment]
Some info on what's actually wrong:

1.  The states switch so fast that Idle state nearly doesn't occur at all, which means no Selling state.
2.  The Quest Grind profile doesn't include Vector3 pos of the vendor, and the search nearby NPC is only 50 range, thus no NPC is found.

- [ ] Add Vendor pos to QuestGrind profile
- [ ] Generate path from player pos to vendor pos
- [ ] Add new state GoingToVendor/TraversingToVendor during which no state change can occur, until nearby final location.

**Comment by Jnnshschl** [comment]
state system got replaced, no longer valid
