### ISSUE TITLE
[FeatureRequest] Allow no combat class

### ISSUE THREAD

**Issue by Bia10** [Jnnshschl/AmeisenBotX#90]
Currently bot will throw exception if we enter ingame without combat class. This isn't very nice for two reasons.

1.  If user starts the bot for first time its very hard to pause the bot before jumping ingame on high-end rigs. Thus its not possible to stop the bot and select combat class without running into exception.

2. Not all engines should require a combat class. Doing profession tasks while at secure location in town doesn't have much need for a combat class.

**Comment by Jnnshschl** [comment]
Should be fixed, if no CombatClass is selected the bot is just going to use autoattacks.
