### ISSUE TITLE
Handle OnMerchantShow when Bot.Target is Null, in AmeisenBot.cs

### ISSUE THREAD

**Issue by funkyshape** [Jnnshschl/AmeisenBotX#99]
Crashes when target gets lost. Try (Bot.Target != null)

https://github.com/Jnnshschl/AmeisenBotX/blob/440418304344fa04cc5f6c6e851e22a783557abd/AmeisenBotX.Core/AmeisenBot.cs#L694

**Comment by Jnnshschl** [comment]
fixed https://github.com/Jnnshschl/AmeisenBotX/commit/4c8406c5311572937c82d6f1f8eabe6b2f9ccf57
